name: Release

on:
  push:
    tags:
      - v*

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Archive data artifacts
        uses: actions/upload-artifact@v1
        with:
          name: data
          path: data
  release:
    needs: archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download data
        uses: actions/download-artifact@v1
        with:
          name: data
      - name: Zip artifacts
        run: zip -r data.zip data
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: data.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
